#!/usr/bin/env bash
#
# To enable this hook, developers should place it in .git/hooks/.
#
# You may adapt the message length check. Currently checking it's longer than
# 15 characters.


ROOT_DIR="$(pwd)/"
PREFIX=$($ROOT_DIR/vendor/bin/drupal yaml:get:value $ROOT_DIR/project.yml project.prefix)
regex="^[^ ].{15,}\."
if ! grep -iqE "$regex" "$1"; then
  echo "Invalid commit message. Commit messages must:"
  echo "* Be at least 15 characters long and end with a period."
  echo "Valid example: Added the new picture field to the article feature."
  exit 1;
fi
