project:
    machine_name: watercooler
    prefix: WC
    human_name: Watercooler
    profile:
        name: lightning
        contrib: true
    local:
        protocol: http
        hostname: '${project.machine_name}.localhost'
git:
    default_branch: master
    remotes:
        - 'git@github.com:jrbeeman/watercooler.git'
    commit_message:
        regex: "^[^ ].{15,}\."
        instructions: |
            Invalid commit message. Commit messages must:

            * Be at least 15 characters long and end with a period.

            Valid example: Added the new picture field to the article feature.
drush:
    aliases:
        remote: '${project.machine_name}.test'
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend setup configured.'''
    frontend-build:
        dir: '${docroot}'
        command: 'echo ''No frontend build configured.'''
    post-deploy-build:
        dir: '${deploy.dir}/docroot/profiles/contrib/lightning'
        command: 'npm run install-libraries'
    post-setup-build:
        dir: '${docroot}/profiles/contrib/lightning'
        command: 'npm run install-libraries'
import: null

