project:
    machine_name: watercooler
    prefix: WC
    human_name: Watercooler
    profile:
        name: lightning
    local:
        protocol: http
        hostname: '${project.machine_name}.localhost'
git:
    default_branch: master
    remotes:
        - 'git@github.com:jrbeeman/watercooler.git'
drush:
    aliases:
        remote: '${project.machine_name}.test'
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend setup configured.'''
    frontend-build:
        dir: '${docroot}'
        command: 'echo ''No frontend build configured.'''
    post-deploy-build:
        dir: '${deploy.dir}/docroot/profiles/contrib/lightning'
        command: 'npm run install-libraries'
    post-setup-build:
        dir: '${docroot}/profiles/contrib/lightning'
        command: 'npm run install-libraries'
import: null
# Un-comment the profiles line in order to run Lightning profile tests.
behat:
  paths:
    # - ${docroot}/modules
    # - ${docroot}/profiles
    - ${repo.root}/tests/behat
