project:
  machine_name: watercooler
  prefix: WC
  human_name: Watercooler
  profile:
    name: lightning
  local:
    protocol: http
    hostname: '${project.machine_name}.localhost'
git:
  default_branch: master
  remotes:
    - 'git@github.com:jrbeeman/watercooler.git'
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
target-hooks:
  frontend-setup:
    dir: '${docroot}'
    command: 'echo ''No frontend setup configured.'''
  frontend-build:
    dir: '${docroot}'
    command: 'echo ''No frontend build configured.'''
  post-deploy-build:
    dir: '${deploy.dir}/docroot/profiles/contrib/lightning'
    command: 'npm run install-libraries'
  post-setup-build:
    dir: '${docroot}/profiles/contrib/lightning'
    command: 'npm run install-libraries'
import: null
modules:
  local:
    enable: [dblog, devel, field_ui, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, field_ui, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, field_ui, views_ui]
  deploy:
    enable: [acquia_connector, shield]
    uninstall: [devel, field_ui, views_ui]
behat:
  paths:
    - '${repo.root}/tests/behat'

