<?php

/**
 * @file
 * Contains decoda.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function decoda_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the decoda module.
    case 'help.page.decoda':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add Decoda text parsing library.') . '</p>';
      return $output;

    default:
  }
}
